
import React from 'react';
import { Info } from 'lucide-react';

export const SECURITY_INFO = {
  NONCE: {
    title: "What is a Nonce?",
    description: "A 'Number Used Once' generated by the server. It prevents Replay Attacks by ensuring that a captured signature cannot be reused in a future session."
  },
  CONTEXT_BINDING: {
    title: "Context-Aware Binding",
    description: "The signature covers not just the nonce, but the entire transaction context (Amount, Recipient, Action). This prevents an attacker from swapping transaction details after a signature is generated."
  },
  RISK_BASED: {
    title: "Risk-Based Access Control",
    description: "Authorization is dynamic. High-risk operations (like account deletion) require stricter validation and higher confidence scores than low-risk ones (like reading profile info)."
  },
  HASH_CHAIN: {
    title: "Tamper-Evident Logs",
    description: "Logs are linked using cryptographic hashes. If one record is changed, the entire chain's integrity is broken, making tampering immediately detectable."
  }
};

export const UI_STRINGS = {
  BANNER: "Academic Cybersecurity Demonstration System",
  DISCLAIMER: "This is a non-functional simulation for educational purposes."
};
